//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLStore.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public string ID_Customer { get; set; }
        public string Name_Cus { get; set; }
        public string Address_Cus { get; set; }
        public string Phone { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Email { get; set; }
    }
}
