//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLStore.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detail_Product
    {
        public string ID_Product { get; set; }
        public string ID_TypeProduct { get; set; }
        public string ID_Supplier { get; set; }
        public Nullable<int> Original_Price { get; set; }
        public string NameProduct { get; set; }
        public string Description_Pro { get; set; }
        public string Image_Path { get; set; }
        public Nullable<int> Amount_Current { get; set; }
    }
}
