//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLStore.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff_Bill
    {
        public string ID_Bill { get; set; }
        public string ID_Staff { get; set; }
    }
}
