//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLStore.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        public string ID_sup { get; set; }
        public string Name_Sup { get; set; }
        public string Address_sup { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string MoreInfo { get; set; }
    }
}
