//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLStore.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Type_product
    {
        public string ID { get; set; }
        public string Type_Product1 { get; set; }
        public Nullable<int> Num_Of_Product { get; set; }
    }
}
